package codegen

import (
	"text/template"

	"github.com/tab58/gql-orm/pkg/schema"
)

const clientTemplate = `// Code generated by gql-orm. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/tab58/gql-orm/pkg/client"
	"github.com/tab58/gql-orm/pkg/driver"
)

// NewClient creates a new gql-orm client backed by the given driver.
// Uses the generated GraphModel and AugmentedSchemaSDL for query validation
// and single-roundtrip Cypher translation.
func NewClient(drv driver.Driver, opts ...client.Option) *client.Client {
	return client.New(GraphModel, AugmentedSchemaSDL, drv, opts...)
}
`

// GenerateClient produces Go source code for a client_gen.go file containing
// a NewClient convenience constructor. The generated NewClient function calls
// client.New with the generated GraphModel and AugmentedSchemaSDL variables.
func GenerateClient(model schema.GraphModel, packageName string) ([]byte, error) {
	return executeTemplate("client", clientTemplate, template.FuncMap{}, model, packageName)
}
