package codegen

import (
	"text/template"

	"github.com/tab58/gql-orm/pkg/schema"
)

const clientTemplate = `// Code generated by gql-orm. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/tab58/gql-orm/pkg/client"
	"github.com/tab58/gql-orm/pkg/driver"
)

// NewClient creates a new gql-orm client backed by the given driver.
// It wires the generated Resolver and gqlgen ExecutableSchema together
// and returns a ready-to-use *client.Client.
func NewClient(drv driver.Driver, opts ...client.Option) *client.Client {
	resolver := &Resolver{Driver: drv}
	es := NewExecutableSchema(Config{Resolvers: resolver})
	return client.New(es, drv, opts...)
}
`

// GenerateClient produces Go source code for a client_gen.go file containing
// a NewClient convenience constructor. The generated NewClient function wires
// the generated Resolver, gqlgen ExecutableSchema, and pkg/client.Client together.
func GenerateClient(model schema.GraphModel, packageName string) ([]byte, error) {
	return executeTemplate("client", clientTemplate, template.FuncMap{}, model, packageName)
}
