package codegen

import (
	"text/template"

	"github.com/tab58/gql-orm/pkg/schema"
)

const mapperTemplate = `// Code generated by gql-orm. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/tab58/gql-orm/pkg/driver"
)

// --- Type conversion helpers ---

func stringFromAny(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	return ""
}

func intFromAny(v any) int {
	switch n := v.(type) {
	case int:
		return n
	case int64:
		return int(n)
	case float64:
		return int(n)
	}
	return 0
}

func float64FromAny(v any) float64 {
	switch n := v.(type) {
	case float64:
		return n
	case int:
		return float64(n)
	case int64:
		return float64(n)
	}
	return 0
}

func boolFromAny(v any) bool {
	if b, ok := v.(bool); ok {
		return b
	}
	return false
}

func stringPtrFromAny(v any) *string {
	if v == nil {
		return nil
	}
	if s, ok := v.(string); ok {
		return &s
	}
	return nil
}

func intPtrFromAny(v any) *int {
	if v == nil {
		return nil
	}
	switch n := v.(type) {
	case int:
		return &n
	case int64:
		i := int(n)
		return &i
	case float64:
		i := int(n)
		return &i
	}
	return nil
}

func float64PtrFromAny(v any) *float64 {
	if v == nil {
		return nil
	}
	switch n := v.(type) {
	case float64:
		return &n
	case int:
		f := float64(n)
		return &f
	case int64:
		f := float64(n)
		return &f
	}
	return nil
}

func boolPtrFromAny(v any) *bool {
	if v == nil {
		return nil
	}
	if b, ok := v.(bool); ok {
		return &b
	}
	return nil
}
{{range .Nodes}}
// --- {{.Name}} conversions ---

func recordTo{{.Name}}(rec driver.Record) *{{.Name}} {
	n := &{{.Name}}{}
{{- range .Fields}}
{{- if .Nullable}}
	if v, ok := rec.Values["{{.Name}}"]; ok && v != nil {
		n.{{goField .Name}} = {{ptrFromAny .GoType}}(v)
	}
{{- else}}
	if v, ok := rec.Values["{{.Name}}"]; ok {
		n.{{goField .Name}} = {{fromAny .GoType}}(v)
	}
{{- end}}
{{- end}}
	return n
}

func recordsTo{{pluralCap .Name}}(records []driver.Record) []*{{.Name}} {
	result := make([]*{{.Name}}, len(records))
	for i, rec := range records {
		result[i] = recordTo{{.Name}}(rec)
	}
	return result
}

func {{lowerFirst .Name}}WhereToMap(where *{{.Name}}Where) map[string]any {
	if where == nil {
		return map[string]any{}
	}
	m := map[string]any{}
{{- range .Fields}}
	if where.{{goField .Name}} != nil {
		m["{{.Name}}"] = *where.{{goField .Name}}
	}
{{- end}}
	return m
}

func {{lowerFirst .Name}}CreateInputToMap(input *{{.Name}}CreateInput) map[string]any {
	m := map[string]any{}
{{- range .Fields}}
{{- if not .IsID}}
{{- if .Nullable}}
	if input.{{goField .Name}} != nil {
		m["{{.Name}}"] = *input.{{goField .Name}}
	}
{{- else}}
	m["{{.Name}}"] = input.{{goField .Name}}
{{- end}}
{{- end}}
{{- end}}
	return m
}

func {{lowerFirst .Name}}UpdateInputToMap(update *{{.Name}}UpdateInput) map[string]any {
	if update == nil {
		return map[string]any{}
	}
	m := map[string]any{}
{{- range .Fields}}
{{- if not .IsID}}
	if update.{{goField .Name}} != nil {
		m["{{.Name}}"] = *update.{{goField .Name}}
	}
{{- end}}
{{- end}}
	return m
}
{{end}}
{{- range propsTypes}}
func recordTo{{.TypeName}}(rec driver.Record) *{{.TypeName}} {
	p := &{{.TypeName}}{}
{{- range .Fields}}
{{- if .Nullable}}
	if v, ok := rec.Values["{{.Name}}"]; ok && v != nil {
		p.{{goField .Name}} = {{ptrFromAny .GoType}}(v)
	}
{{- else}}
	if v, ok := rec.Values["{{.Name}}"]; ok {
		p.{{goField .Name}} = {{fromAny .GoType}}(v)
	}
{{- end}}
{{- end}}
	return p
}

func {{lowerFirst .TypeName}}CreateInputToMap(input *{{.TypeName}}CreateInput) map[string]any {
	if input == nil {
		return map[string]any{}
	}
	m := map[string]any{}
{{- range .Fields}}
{{- if .Nullable}}
	if input.{{goField .Name}} != nil {
		m["{{.Name}}"] = *input.{{goField .Name}}
	}
{{- else}}
	m["{{.Name}}"] = input.{{goField .Name}}
{{- end}}
{{- end}}
	return m
}

func {{lowerFirst .TypeName}}UpdateInputToMap(input *{{.TypeName}}UpdateInput) map[string]any {
	if input == nil {
		return map[string]any{}
	}
	m := map[string]any{}
{{- range .Fields}}
	if input.{{goField .Name}} != nil {
		m["{{.Name}}"] = *input.{{goField .Name}}
	}
{{- end}}
	return m
}
{{end}}
`

// GenerateMappers produces Go source code for type conversion functions.
// Generates record-to-model, where-to-map, createInput-to-map, and
// updateInput-to-map converters for each node type.
func GenerateMappers(model schema.GraphModel, packageName string) ([]byte, error) {
	rels := model.Relationships
	funcMap := template.FuncMap{
		"pluralCap":  pluralCapitalized,
		"lowerFirst": lowerFirst,
		"goField":    goFieldName,
		"fromAny":    fromAnyFuncName,
		"ptrFromAny": ptrFromAnyFuncName,
		"propsTypes": func() []schema.PropertiesDefinition {
			seen := map[string]bool{}
			var result []schema.PropertiesDefinition
			for _, r := range rels {
				if r.Properties != nil && !seen[r.Properties.TypeName] {
					seen[r.Properties.TypeName] = true
					result = append(result, *r.Properties)
				}
			}
			return result
		},
	}
	return executeTemplate("mappers", mapperTemplate, funcMap, model, packageName)
}
