package codegen

const resolverTemplate = `// Code generated by gql-orm. DO NOT EDIT.
package {{.PackageName}}

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"

	"github.com/tab58/gql-orm/pkg/cypher"
	"github.com/tab58/gql-orm/pkg/driver"
)

type Resolver struct {
	Driver driver.Driver
}

// Compile-time check that Resolver implements gqlgen's ResolverRoot interface.
var _ ResolverRoot = &Resolver{}

type queryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }

func (r *Resolver) Query() QueryResolver       { return &queryResolver{r} }
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

const defaultPageSize = 10

func parseConnectionPagination(first *int, after *string) (limit, offset int) {
	limit = defaultPageSize
	if first != nil {
		limit = *first
	}
	if after != nil {
		decoded, err := decodeCursor(*after)
		if err == nil {
			offset = decoded + 1
		}
	}
	return limit, offset
}

func encodeCursor(offset int) string {
	return base64.StdEncoding.EncodeToString([]byte(strconv.Itoa(offset)))
}

func decodeCursor(cursor string) (int, error) {
	data, err := base64.StdEncoding.DecodeString(cursor)
	if err != nil {
		return 0, fmt.Errorf("invalid cursor: %w", err)
	}
	return strconv.Atoi(string(data))
}

{{range .Nodes}}{{$node := .}}
// --- {{.Name}} whereToClause + sortToFields ---

func {{lowerFirst .Name}}WhereToClause(where *{{.Name}}Where) cypher.WhereClause {
	if where == nil {
		return cypher.WhereClause{}
	}
	var preds []cypher.Predicate
{{range .Fields}}
	if where.{{goField .Name}} != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpEq, Value: where.{{goField .Name}}})
	}
{{if not (eq (baseType .GraphQLType) "Boolean")}}
	if where.{{goField .Name}}Gt != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpGT, Value: where.{{goField .Name}}Gt})
	}
	if where.{{goField .Name}}Gte != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpGTE, Value: where.{{goField .Name}}Gte})
	}
	if where.{{goField .Name}}Lt != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpLT, Value: where.{{goField .Name}}Lt})
	}
	if where.{{goField .Name}}Lte != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpLTE, Value: where.{{goField .Name}}Lte})
	}
{{end}}
{{if or (eq (baseType .GraphQLType) "String") (eq (baseType .GraphQLType) "ID")}}
	if where.{{goField .Name}}Contains != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpContains, Value: where.{{goField .Name}}Contains})
	}
	if where.{{goField .Name}}StartsWith != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpStartsWith, Value: where.{{goField .Name}}StartsWith})
	}
	if where.{{goField .Name}}EndsWith != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpEndsWith, Value: where.{{goField .Name}}EndsWith})
	}
	if where.{{goField .Name}}Regex != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpRegex, Value: where.{{goField .Name}}Regex})
	}
{{end}}
	if where.{{goField .Name}}In != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpIn, Value: where.{{goField .Name}}In})
	}
	if where.{{goField .Name}}Nin != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpNotIn, Value: where.{{goField .Name}}Nin})
	}
	if where.{{goField .Name}}Not != nil {
		preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpNEq, Value: where.{{goField .Name}}Not})
	}
	if where.{{goField .Name}}IsNull != nil {
		if *where.{{goField .Name}}IsNull {
			preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpIsNull})
		} else {
			preds = append(preds, cypher.Predicate{Field: "{{.Name}}", Op: cypher.OpIsNotNull})
		}
	}
{{end}}
	clause := cypher.WhereClause{Predicates: preds}
	if where.And != nil {
		for _, sub := range where.And {
			clause.AND = append(clause.AND, {{lowerFirst .Name}}WhereToClause(sub))
		}
	}
	if where.Or != nil {
		for _, sub := range where.Or {
			clause.OR = append(clause.OR, {{lowerFirst .Name}}WhereToClause(sub))
		}
	}
	if where.Not != nil {
		notClause := {{lowerFirst .Name}}WhereToClause(where.Not)
		clause.NOT = &notClause
	}
	return clause
}

func {{lowerFirst .Name}}SortToFields(sort []*{{.Name}}Sort) []cypher.SortField {
	if len(sort) == 0 {
		return nil
	}
	var fields []cypher.SortField
	for _, s := range sort {
{{range .Fields}}
		if s.{{goField .Name}} != nil {
			dir := cypher.SortASC
			if *s.{{goField .Name}} == "DESC" {
				dir = cypher.SortDESC
			}
			fields = append(fields, cypher.SortField{Field: "{{.Name}}", Direction: dir})
		}
{{end}}
	}
	return fields
}

// --- {{.Name}} query resolvers ---

func (r *queryResolver) {{pluralCap .Name}}(ctx context.Context, where *{{.Name}}Where, sort []*{{.Name}}Sort) ([]*{{.Name}}, error) {
	clause := {{lowerFirst .Name}}WhereToClause(where)
	sortFields := {{lowerFirst .Name}}SortToFields(sort)
	stmt := cypher.NodeMatch("{{.Name}}", clause, sortFields)
	result, err := r.Driver.Execute(ctx, stmt)
	if err != nil {
		return nil, fmt.Errorf("query {{plural .Name}}: %w", err)
	}
	return recordsTo{{pluralCap .Name}}(result.Records), nil
}

func (r *queryResolver) {{pluralCap .Name}}Connection(ctx context.Context, first *int, after *string, where *{{.Name}}Where, sort []*{{.Name}}Sort) (*{{pluralCap .Name}}Connection, error) {
	clause := {{lowerFirst .Name}}WhereToClause(where)
	sortFields := {{lowerFirst .Name}}SortToFields(sort)
	limit, offset := parseConnectionPagination(first, after)
	stmt := cypher.ConnectionQuery("{{.Name}}", clause, sortFields, limit, offset)
	result, err := r.Driver.Execute(ctx, stmt)
	if err != nil {
		return nil, fmt.Errorf("query {{plural .Name}}Connection: %w", err)
	}
	countStmt := cypher.ConnectionCount("{{.Name}}", clause)
	countResult, err := r.Driver.Execute(ctx, countStmt)
	if err != nil {
		return nil, fmt.Errorf("count {{plural .Name}}Connection: %w", err)
	}
	totalCount := 0
	if len(countResult.Records) > 0 {
		totalCount = intFromAny(countResult.Records[0].Values["count"])
	}
	records := result.Records
	edges := make([]*{{.Name}}Edge, len(records))
	for i, rec := range records {
		cursor := encodeCursor(offset + i)
		edges[i] = &{{.Name}}Edge{
			Node:   recordTo{{.Name}}(rec),
			Cursor: cursor,
		}
	}
	hasNext := offset+len(records) < totalCount
	hasPrev := offset > 0
	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}
	return &{{pluralCap .Name}}Connection{
		Edges:      edges,
		TotalCount: totalCount,
		PageInfo: &PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: hasPrev,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}, nil
}

// --- {{.Name}} mutation resolvers ---
{{if hasRels .Name}}
func (r *mutationResolver) Create{{pluralCap .Name}}(ctx context.Context, input []*{{.Name}}CreateInput) (*Create{{pluralCap .Name}}MutationResponse, error) {
	var results []*{{.Name}}
	for _, item := range input {
		tx, err := r.Driver.BeginTx(ctx)
		if err != nil {
			return nil, fmt.Errorf("create {{pluralCap .Name}}: begin tx: %w", err)
		}
		defer tx.Rollback(ctx)

		nodeMap := {{lowerFirst .Name}}CreateInputToMap(item)
		stmt := cypher.NodeCreate("{{.Name}}", nodeMap)
		result, err := tx.Execute(ctx, stmt)
		if err != nil {
			return nil, fmt.Errorf("create {{pluralCap .Name}}: %w", err)
		}
{{range relsForNode .Name}}
		if item.{{goField .FieldName}} != nil {
			for _, createField := range item.{{goField .FieldName}}.Create {
				nodeInput := {{lowerFirst .ToNode}}CreateInputToMap(createField.Node)
				nodeStmt := cypher.NodeCreate("{{.ToNode}}", nodeInput)
				if _, err := tx.Execute(ctx, nodeStmt); err != nil {
					return nil, fmt.Errorf("create {{$node.Name}}: nested create {{.ToNode}}: %w", err)
				}
				edgeProps := map[string]any{}
{{- if .Properties}}
				if createField.Edge != nil {
					edgeProps = {{lowerFirst .Properties.TypeName}}CreateInputToMap(createField.Edge)
				}
{{- end}}
				relStmt := cypher.RelCreate("{{$node.Name}}", cypher.EqualityWhere(nodeMap), "{{.RelType}}", "{{.ToNode}}", cypher.EqualityWhere(nodeInput), edgeProps)
				if _, err := tx.Execute(ctx, relStmt); err != nil {
					return nil, fmt.Errorf("create {{$node.Name}}: create {{.RelType}} rel: %w", err)
				}
			}
			for _, connectField := range item.{{goField .FieldName}}.Connect {
				where := {{lowerFirst .ToNode}}WhereToMap(connectField.Where)
				matchStmt := cypher.NodeMatch("{{.ToNode}}", cypher.EqualityWhere(where), nil)
				if _, err := tx.Execute(ctx, matchStmt); err != nil {
					return nil, fmt.Errorf("create {{$node.Name}}: connect match {{.ToNode}}: %w", err)
				}
				edgeProps := map[string]any{}
{{- if .Properties}}
				if connectField.Edge != nil {
					edgeProps = {{lowerFirst .Properties.TypeName}}CreateInputToMap(connectField.Edge)
				}
{{- end}}
				relStmt := cypher.RelCreate("{{$node.Name}}", cypher.EqualityWhere(nodeMap), "{{.RelType}}", "{{.ToNode}}", cypher.EqualityWhere(where), edgeProps)
				if _, err := tx.Execute(ctx, relStmt); err != nil {
					return nil, fmt.Errorf("create {{$node.Name}}: connect {{.RelType}} rel: %w", err)
				}
			}
		}
{{end}}
		if err := tx.Commit(ctx); err != nil {
			return nil, fmt.Errorf("create {{pluralCap .Name}}: commit: %w", err)
		}
		results = append(results, recordsTo{{pluralCap .Name}}(result.Records)...)
	}
	return &Create{{pluralCap .Name}}MutationResponse{{"{"}}{{pluralCap .Name}}: results}, nil
}
{{else}}
func (r *mutationResolver) Create{{pluralCap .Name}}(ctx context.Context, input []*{{.Name}}CreateInput) (*Create{{pluralCap .Name}}MutationResponse, error) {
	var results []*{{.Name}}
	for _, item := range input {
		nodeMap := {{lowerFirst .Name}}CreateInputToMap(item)
		stmt := cypher.NodeCreate("{{.Name}}", nodeMap)
		result, err := r.Driver.ExecuteWrite(ctx, stmt)
		if err != nil {
			return nil, fmt.Errorf("create {{pluralCap .Name}}: %w", err)
		}
		results = append(results, recordsTo{{pluralCap .Name}}(result.Records)...)
	}
	return &Create{{pluralCap .Name}}MutationResponse{{"{"}}{{pluralCap .Name}}: results}, nil
}
{{end}}
{{if hasRels .Name}}
func (r *mutationResolver) Update{{pluralCap .Name}}(ctx context.Context, where *{{.Name}}Where, update *{{.Name}}UpdateInput) (*Update{{pluralCap .Name}}MutationResponse, error) {
	clause := {{lowerFirst .Name}}WhereToClause(where)
	tx, err := r.Driver.BeginTx(ctx)
	if err != nil {
		return nil, fmt.Errorf("update {{pluralCap .Name}}: begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	updateMap := {{lowerFirst .Name}}UpdateInputToMap(update)
	stmt := cypher.NodeUpdate("{{.Name}}", clause, updateMap)
	result, err := tx.Execute(ctx, stmt)
	if err != nil {
		return nil, fmt.Errorf("update {{pluralCap .Name}}: %w", err)
	}
{{range relsForNode .Name}}
	if update != nil && update.{{goField .FieldName}} != nil {
		relInput := update.{{goField .FieldName}}
		if relInput.Create != nil {
			for _, createField := range relInput.Create {
				nodeInput := {{lowerFirst .ToNode}}CreateInputToMap(createField.Node)
				nodeStmt := cypher.NodeCreate("{{.ToNode}}", nodeInput)
				if _, err := tx.Execute(ctx, nodeStmt); err != nil {
					return nil, fmt.Errorf("update {{$node.Name}}: nested create {{.ToNode}}: %w", err)
				}
				edgeProps := map[string]any{}
{{- if .Properties}}
				if createField.Edge != nil {
					edgeProps = {{lowerFirst .Properties.TypeName}}CreateInputToMap(createField.Edge)
				}
{{- end}}
				relStmt := cypher.RelCreate("{{$node.Name}}", clause, "{{.RelType}}", "{{.ToNode}}", cypher.EqualityWhere(nodeInput), edgeProps)
				if _, err := tx.Execute(ctx, relStmt); err != nil {
					return nil, fmt.Errorf("update {{$node.Name}}: create {{.RelType}} rel: %w", err)
				}
			}
		}
		if relInput.Connect != nil {
			for _, connectField := range relInput.Connect {
				connectWhere := {{lowerFirst .ToNode}}WhereToMap(connectField.Where)
				edgeProps := map[string]any{}
{{- if .Properties}}
				if connectField.Edge != nil {
					edgeProps = {{lowerFirst .Properties.TypeName}}CreateInputToMap(connectField.Edge)
				}
{{- end}}
				relStmt := cypher.RelCreate("{{$node.Name}}", clause, "{{.RelType}}", "{{.ToNode}}", cypher.EqualityWhere(connectWhere), edgeProps)
				if _, err := tx.Execute(ctx, relStmt); err != nil {
					return nil, fmt.Errorf("update {{$node.Name}}: connect {{.RelType}} rel: %w", err)
				}
			}
		}
		if relInput.Disconnect != nil {
			for _, disconnectField := range relInput.Disconnect {
				disconnectWhere := {{lowerFirst .ToNode}}WhereToClause(disconnectField.Where)
				discStmt := cypher.RelDisconnect("{{$node.Name}}", clause, "{{.RelType}}", "{{.ToNode}}", disconnectWhere)
				if _, err := tx.Execute(ctx, discStmt); err != nil {
					return nil, fmt.Errorf("update {{$node.Name}}: disconnect {{.RelType}} rel: %w", err)
				}
			}
		}
		if relInput.Update != nil {
			nodeSet := {{lowerFirst .ToNode}}UpdateInputToMap(relInput.Update.Node)
			edgeSet := map[string]any{}
{{- if .Properties}}
			if relInput.Update.Edge != nil {
				edgeSet = {{lowerFirst .Properties.TypeName}}UpdateInputToMap(relInput.Update.Edge)
			}
{{- end}}
			updateWhere := {{lowerFirst .ToNode}}WhereToClause(relInput.Update.Where)
			updateStmt := cypher.NestedUpdate("{{$node.Name}}", clause, "{{.RelType}}", "{{.ToNode}}", updateWhere, nodeSet, edgeSet)
			if _, err := tx.Execute(ctx, updateStmt); err != nil {
				return nil, fmt.Errorf("update {{$node.Name}}: nested update {{.ToNode}}: %w", err)
			}
		}
		if relInput.Delete != nil {
			for _, deleteField := range relInput.Delete {
				deleteWhere := {{lowerFirst .ToNode}}WhereToClause(deleteField.Where)
				delStmt := cypher.NestedDelete("{{$node.Name}}", clause, "{{.RelType}}", "{{.ToNode}}", deleteWhere)
				if _, err := tx.Execute(ctx, delStmt); err != nil {
					return nil, fmt.Errorf("update {{$node.Name}}: nested delete {{.ToNode}}: %w", err)
				}
			}
		}
	}
{{end}}
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("update {{pluralCap .Name}}: commit: %w", err)
	}
	return &Update{{pluralCap .Name}}MutationResponse{{"{"}}{{pluralCap .Name}}: recordsTo{{pluralCap .Name}}(result.Records)}, nil
}
{{else}}
func (r *mutationResolver) Update{{pluralCap .Name}}(ctx context.Context, where *{{.Name}}Where, update *{{.Name}}UpdateInput) (*Update{{pluralCap .Name}}MutationResponse, error) {
	clause := {{lowerFirst .Name}}WhereToClause(where)
	updateMap := {{lowerFirst .Name}}UpdateInputToMap(update)
	stmt := cypher.NodeUpdate("{{.Name}}", clause, updateMap)
	result, err := r.Driver.ExecuteWrite(ctx, stmt)
	if err != nil {
		return nil, fmt.Errorf("update {{pluralCap .Name}}: %w", err)
	}
	return &Update{{pluralCap .Name}}MutationResponse{{"{"}}{{pluralCap .Name}}: recordsTo{{pluralCap .Name}}(result.Records)}, nil
}
{{end}}

func (r *mutationResolver) Delete{{pluralCap .Name}}(ctx context.Context, where *{{.Name}}Where) (*DeleteInfo, error) {
	clause := {{lowerFirst .Name}}WhereToClause(where)
	stmt := cypher.NodeDelete("{{.Name}}", clause)
	_, err := r.Driver.ExecuteWrite(ctx, stmt)
	if err != nil {
		return nil, fmt.Errorf("delete {{pluralCap .Name}}: %w", err)
	}
	return &DeleteInfo{NodesDeleted: 1, RelationshipsDeleted: 0}, nil
}
{{if hasObjectResolver .Name}}
// --- {{.Name}} object resolver ---

type {{lowerFirst .Name}}Resolver struct{ *Resolver }

func (r *Resolver) {{.Name}}() {{.Name}}Resolver { return &{{lowerFirst .Name}}Resolver{r} }
{{if hasCypherFields .Name}}
// --- {{.Name}} @cypher field resolvers ---
{{range .CypherFields}}
func (r *{{lowerFirst $node.Name}}Resolver) {{goField .Name}}(ctx context.Context, obj *{{$node.Name}}{{range .Arguments}}, {{.Name}} {{.GoType}}{{end}}) ({{.GoType}}, error) {
	parentWhere := cypher.EqualityWhere(map[string]any{"id": obj.ID})
{{- if .Arguments}}
	args := map[string]any{
{{- range .Arguments}}
		"{{.Name}}": {{.Name}},
{{- end}}
	}
	stmt := cypher.CypherDirective("{{$node.Name}}", parentWhere, "{{.Statement}}", args)
{{- else}}
	stmt := cypher.CypherDirective("{{$node.Name}}", parentWhere, "{{.Statement}}", nil)
{{- end}}
	result, err := r.Driver.Execute(ctx, stmt)
	if err != nil {
		return {{zeroValue .GoType}}, fmt.Errorf("@cypher {{.Name}}: %w", err)
	}
{{- if .IsList}}
	return recordsTo{{pluralCap (listElemType .GoType)}}(result.Records), nil
{{- else}}
	if len(result.Records) == 0 {
		return {{zeroValue .GoType}}, nil
	}
	return {{cypherHelper .GoType}}(result.Records[0].Values["__cypher_result"]), nil
{{- end}}
}
{{end}}
{{end}}

type {{.Name}}Resolver interface {
{{- if hasCypherFields .Name}}
{{- range .CypherFields}}
	{{goField .Name}}(ctx context.Context, obj *{{$node.Name}}{{range .Arguments}}, {{.Name}} {{.GoType}}{{end}}) ({{.GoType}}, error)
{{- end}}
{{- end}}
{{- if hasRels .Name}}
{{- range relsForNode .Name}}
	{{goField .FieldName}}Connection(ctx context.Context, obj *{{$node.Name}}, first *int, after *string, where *{{.ToNode}}Where, sort []*{{.ToNode}}Sort) (*{{$node.Name}}{{goField .FieldName}}Connection, error)
{{- end}}
{{- end}}
}
{{end}}
{{if hasRels .Name}}
// --- {{.Name}} connection resolvers ---
{{range relsForNode .Name}}
func (r *{{lowerFirst $node.Name}}Resolver) {{goField .FieldName}}Connection(ctx context.Context, obj *{{$node.Name}}, first *int, after *string, where *{{.ToNode}}Where, sort []*{{.ToNode}}Sort) (*{{$node.Name}}{{goField .FieldName}}Connection, error) {
	parentWhere := cypher.EqualityWhere(map[string]any{"id": obj.ID})
	childWhere := {{lowerFirst .ToNode}}WhereToClause(where)
	childSort := {{lowerFirst .ToNode}}SortToFields(sort)
	limit, offset := parseConnectionPagination(first, after)
	stmt := cypher.RelConnectionQuery("{{$node.Name}}", parentWhere, "{{.RelType}}", "{{.ToNode}}", cypher.Direction{{.Direction}}, childWhere, childSort, limit, offset)
	result, err := r.Driver.Execute(ctx, stmt)
	if err != nil {
		return nil, fmt.Errorf("{{.FieldName}}Connection query: %w", err)
	}
	countStmt := cypher.RelConnectionCount("{{$node.Name}}", parentWhere, "{{.RelType}}", "{{.ToNode}}", cypher.Direction{{.Direction}}, childWhere)
	countResult, err := r.Driver.Execute(ctx, countStmt)
	if err != nil {
		return nil, fmt.Errorf("{{.FieldName}}Connection count: %w", err)
	}
	totalCount := 0
	if len(countResult.Records) > 0 {
		totalCount = intFromAny(countResult.Records[0].Values["count"])
	}
	records := result.Records
	edges := make([]*{{$node.Name}}{{goField .FieldName}}Edge, len(records))
	for i, rec := range records {
		cursor := encodeCursor(offset + i)
		edges[i] = &{{$node.Name}}{{goField .FieldName}}Edge{
			Node:   recordTo{{.ToNode}}(rec),
			Cursor: cursor,
{{- if .Properties}}
			Properties: recordTo{{.Properties.TypeName}}(rec),
{{- end}}
		}
	}
	hasNext := offset+len(records) < totalCount
	hasPrev := offset > 0
	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}
	return &{{$node.Name}}{{goField .FieldName}}Connection{
		Edges:      edges,
		TotalCount: totalCount,
		PageInfo: &PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: hasPrev,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}, nil
}
{{end}}
{{end}}
{{end}}
{{range cypherHelpers .Nodes}}
func {{.FuncName}}(val any) {{.GoType}} {
	if val == nil {
		return {{zeroValue .GoType}}
	}
{{- if .IsPtr}}
	v, ok := val.({{.BaseType}})
	if !ok {
		return {{zeroValue .GoType}}
	}
	return &v
{{- else}}
	v, ok := val.({{.GoType}})
	if !ok {
		return {{zeroValue .GoType}}
	}
	return v
{{- end}}
}
{{end}}
`

