package codegen

import (
	"strings"
	"testing"
)

// TestGenerateScalars_KnownScalar verifies that a known custom scalar (DateTime)
// produces a type alias to time.Time with the correct import.
func TestGenerateScalars_KnownScalar(t *testing.T) {
	src, err := GenerateScalars([]string{"DateTime"}, "generated")
	if err != nil {
		t.Fatalf("GenerateScalars returned error: %v", err)
	}
	content := string(src)
	if !strings.Contains(content, "package generated") {
		t.Error("missing 'package generated'")
	}
	if !strings.Contains(content, `"time"`) {
		t.Error("missing 'time' import")
	}
	if !strings.Contains(content, "type DateTime = time.Time") {
		t.Errorf("missing 'type DateTime = time.Time' in:\n%s", content)
	}
}

// TestGenerateScalars_UnknownScalar verifies that an unrecognized custom scalar
// produces a type alias to any.
func TestGenerateScalars_UnknownScalar(t *testing.T) {
	src, err := GenerateScalars([]string{"Money"}, "generated")
	if err != nil {
		t.Fatalf("GenerateScalars returned error: %v", err)
	}
	content := string(src)
	if !strings.Contains(content, "type Money = any") {
		t.Errorf("missing 'type Money = any' in:\n%s", content)
	}
	// Unknown scalar should not add any imports.
	if strings.Contains(content, "import") {
		t.Errorf("unexpected import block for unknown scalar in:\n%s", content)
	}
}

// TestGenerateScalars_MixedScalars verifies that a mix of known and unknown
// scalars produces correct aliases and imports.
func TestGenerateScalars_MixedScalars(t *testing.T) {
	src, err := GenerateScalars([]string{"BigInt", "DateTime", "Money"}, "mypackage")
	if err != nil {
		t.Fatalf("GenerateScalars returned error: %v", err)
	}
	content := string(src)
	if !strings.Contains(content, "package mypackage") {
		t.Error("missing 'package mypackage'")
	}
	if !strings.Contains(content, `"time"`) {
		t.Error("missing 'time' import for DateTime")
	}
	if !strings.Contains(content, "type BigInt = int64") {
		t.Errorf("missing 'type BigInt = int64' in:\n%s", content)
	}
	if !strings.Contains(content, "type DateTime = time.Time") {
		t.Errorf("missing 'type DateTime = time.Time' in:\n%s", content)
	}
	if !strings.Contains(content, "type Money = any") {
		t.Errorf("missing 'type Money = any' in:\n%s", content)
	}
}

// TestGenerateScalars_EmptyList verifies that an empty scalar list returns nil.
func TestGenerateScalars_EmptyList(t *testing.T) {
	src, err := GenerateScalars([]string{}, "generated")
	if err != nil {
		t.Fatalf("GenerateScalars returned error: %v", err)
	}
	if src != nil {
		t.Errorf("expected nil for empty scalar list, got %d bytes", len(src))
	}
}

// TestGenerateScalars_EmptyPackageName verifies that an empty package name returns an error.
func TestGenerateScalars_EmptyPackageName(t *testing.T) {
	_, err := GenerateScalars([]string{"DateTime"}, "")
	if err == nil {
		t.Fatal("GenerateScalars with empty package name should return error")
	}
}

// TestGenerateScalars_GeneratedCodeHeader verifies the generated code header.
func TestGenerateScalars_GeneratedCodeHeader(t *testing.T) {
	src, err := GenerateScalars([]string{"DateTime"}, "generated")
	if err != nil {
		t.Fatalf("GenerateScalars returned error: %v", err)
	}
	if !strings.Contains(string(src), "Code generated by gormql. DO NOT EDIT.") {
		t.Error("missing generated code header")
	}
}

// TestGenerateScalars_DeduplicatesImports verifies that multiple scalars using
// the same import (e.g., DateTime and Date both use "time") produce a single import.
func TestGenerateScalars_DeduplicatesImports(t *testing.T) {
	src, err := GenerateScalars([]string{"Date", "DateTime", "Time"}, "generated")
	if err != nil {
		t.Fatalf("GenerateScalars returned error: %v", err)
	}
	content := string(src)
	// Should have exactly one "time" import, not three.
	count := strings.Count(content, `"time"`)
	if count != 1 {
		t.Errorf("expected 1 'time' import, got %d in:\n%s", count, content)
	}
}
