package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/tab58/go-ormql/pkg/schema"
)

// GenerateScalars produces Go source code containing type aliases for custom
// GraphQL scalars. Known scalars (DateTime, Date, etc.) are aliased to their
// mapped Go types. Unknown custom scalars are aliased to any so generated code
// compiles without a hand-written scalars.go.
func GenerateScalars(customScalars []string, packageName string) ([]byte, error) {
	if packageName == "" {
		return nil, fmt.Errorf("packageName must not be empty")
	}
	if len(customScalars) == 0 {
		return nil, nil
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by gormql. DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// Collect imports needed for known scalars.
	imports := collectScalarImports(customScalars)
	if len(imports) > 0 {
		sb.WriteString("import (\n")
		for _, imp := range imports {
			sb.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		sb.WriteString(")\n\n")
	}

	// Emit type aliases for each custom scalar.
	for _, name := range customScalars {
		if scalar, ok := schema.LookupScalarGoType(name); ok {
			sb.WriteString(fmt.Sprintf("// %s is the Go type for the GraphQL %s scalar.\n", name, name))
			sb.WriteString(fmt.Sprintf("type %s = %s\n\n", name, scalar.GoType))
		} else {
			sb.WriteString(fmt.Sprintf("// %s is an unrecognized custom scalar. Replace with a concrete type.\n", name))
			sb.WriteString(fmt.Sprintf("type %s = any\n\n", name))
		}
	}

	return format.Source([]byte(sb.String()))
}

// collectScalarImports returns the sorted, deduplicated import paths needed by
// the custom scalars present in the schema.
func collectScalarImports(customScalars []string) []string {
	seen := map[string]bool{}
	for _, name := range customScalars {
		if scalar, ok := schema.LookupScalarGoType(name); ok && scalar.ImportPath != "" {
			seen[scalar.ImportPath] = true
		}
	}
	imports := make([]string, 0, len(seen))
	for imp := range seen {
		imports = append(imports, imp)
	}
	sort.Strings(imports)
	return imports
}
